version: "3"

name: side-projects

services:
  caddy:
    container_name: caddy
    image: caddy
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy-config:/config
      - caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
  maps-ui:
    container_name: maps-ui
    image: ghcr.io/milindtheengineer/react-demo-maps:main
    restart: on-failure
  maps:
    container_name: maps
    image: ghcr.io/milindtheengineer/custom-http-server:main
    restart: on-failure
    volumes:
      - /etc/new_area_1.pmtiles:/app/new_area_1.pmtiles
  workout-tracker-ui:
    container_name: workout-tracker-ui
    image: ghcr.io/milindtheengineer/workout-tracker-ui:v0.0.12
    restart: on-failure
  workout-tracker-server:
    container_name: workout-tracker-server
    image: ghcr.io/milindtheengineer/workout-tracker-server:v0.0.14
    restart: on-failure
    volumes:
      - /etc/mydb:/etc/mydb
    environment:
      - SERVER_DBPATH=/etc/mydb
      - SERVER_SIGNINGKEY=zzzz
      - SERVER_GOOGLETOKEN=zzzz
volumes:
  caddy-config:
  caddy-data:
